apiVersion: "camel.apache.org/v1alpha1"
kind: "Integration"
metadata:
  name: "example"
  namespace: "myproject"
spec:
  replicas: 1
  routes:
   - id: timer
     route:
      - timer:tick
      - log:info
