apiVersion: "camel.apache.org/v1alpha1"
kind: "Integration"
metadata:
  name: "example"
spec:
  replicas: 1
  flows:
   - id: timer
     steps:
     - type: endpoint
       uri: timer:tick
     - type: endpoint
       uri: log:info
